version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass1234$$"
      ACCEPT_EULA: "Y"
      MSSQL_DB: Idp
    networks:
      - idpnet
  idp:
    # replace username/repo:tag with your name and image details
    build: 
      context: .
      dockerfile: dockerfiles/idp/Dockerfile
    image: idp-server
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Idp: "Server=db;Database=Idp;User=sa;Password=Pass1234$$;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80"
    depends_on:
      - db  
    networks:
      - idpnet
  product:
    # replace username/repo:tag with your name and image details
    build: 
      context: .
      dockerfile: dockerfiles/api/Product
    image: api/product
    environment:
      Idp__Authority: "http://idp"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "10001:80"
    depends_on:
      - idp
      - db  
    networks:
      - idpnet       
networks:
  idpnet: